# Generated by Django 4.2.16 on 2024-11-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0012_device_delete_devicefingerprint_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Manager", "Manager"),
                    ("Customer", "Customer"),
                ],
                default="Customer",
                max_length=10,
            ),
        ),
    ]
